<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">porträt</span></h1>

    <p>
       Porträt is an open-source profile managment system.  It allows you to create a profile and then share it with other sites
       using a simple and secure api.
    </p>

    
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Follow Development</h3>
            </div>
            <div class="panel-body">
                <p>
                    porträt is under active development. If you are
                    interested in following the development of porträt, you can check
                    <a href="">GitHub Issues</a>
                    
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">porträt api</h3>
            </div>
            <div class="panel-body">
                <p>
                    Keep tabs on the docs to learn about porträt's secure api
                </p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Help &amp; Support</h3>
            </div>
            <div class="panel-body">
                <p>
                   If you need any assistance, please check out the wiki or post any issues to GitHub
                </p>

            </div>
        </div>
    </div>
</div>
